### ISSUE TITLE
No

### ISSUE THREAD

**Issue by armenium** [ernieIzde8ski/ratbot#14]
Das Oberkommando der Wehrmacht (OKW) zählte mit dem Oberkommando des Heeres (OKH), dem Oberkommando der Marine (OKM) und dem Oberkommando der Luftwaffe (OKL) zu den höchsten Stabsorganisationen der Wehrmacht. Das OKW und die Oberkommandos der drei Teilstreitkräfte übernahmen in ihrem jeweiligen Zuständigkeitsbereich Planungsaufgaben. Sie waren dem Obersten Befehlshaber der Wehrmacht, Adolf Hitler, unterstellt. Einen Befehlsweg vom OKW zu den anderen Oberkommandos, die über eigene Generalstäbe verfügten, gab es nicht.

_Originally posted by @ernieIzde8ski in https://github.com/ernieIzde8ski/ratbot/issues/9#issuecomment-803059048_

Stop this

**Comment by ernieIzde8ski** [comment]
you are just Bitch

**Comment by armenium** [comment]
You
