### ISSUE TITLE
Cannot ping everyone

### ISSUE THREAD

**Issue by armenium** [ernieIzde8ski/ratbot#9]
Please resolve this bug at once, ratbot is Useless now

**Comment by armenium** [comment]
@ernieIzde8ski Please

**Comment by myerDOT** [comment]
Yeah I Happen to have the Same issue..................... It Really takes away from the experience!!!!!!!!!!

**Comment by ernieIzde8ski** [comment]
[ok liberals now host it yourselves](https://github.com/ernieIzde8ski/ratbot/commit/e05f789162e97325e146456baffa79eff68ddf12)

**Comment by armenium** [comment]
Nope

**Comment by armenium** [comment]
Still waiting on this to be Fixed !!!!!!!!

**Comment by ernieIzde8ski** [comment]
The issue is closed therefore it is solved

**Comment by armenium** [comment]
Nope! You are a bad devloper . I am reporteing you to Hypixel admin

**Comment by ernieIzde8ski** [comment]
If you will Host it you are Self then you will be able to ping Everyone .

**Comment by armenium** [comment]
![2020-08-13_4](https://user-images.githubusercontent.com/53126710/108649719-be232480-7472-11eb-8d5a-bded2729b682.png)
You

**Comment by ernieIzde8ski** [comment]
Based

**Comment by myerDOT** [comment]
You is are Bad Developer........... Did you happen to code the hypixel api?

**Comment by ernieIzde8ski** [comment]
I did, and I am very proud of my work!

**Comment by armenium** [comment]
You are the bane of Many teenagers with No life's Existence ....................

**Comment by ernieIzde8ski** [comment]
Get Owne

**Comment by myerDOT** [comment]
die

**Comment by armenium** [comment]
The what

**Comment by ernieIzde8ski** [comment]
Das Oberkommando der Wehrmacht (OKW) zählte mit dem Oberkommando des Heeres (OKH), dem Oberkommando der Marine (OKM) und dem Oberkommando der Luftwaffe (OKL) zu den höchsten Stabsorganisationen der Wehrmacht. Das OKW und die Oberkommandos der drei Teilstreitkräfte übernahmen in ihrem jeweiligen Zuständigkeitsbereich Planungsaufgaben. Sie waren dem Obersten Befehlshaber der Wehrmacht, Adolf Hitler, unterstellt. Einen Befehlsweg vom OKW zu den anderen Oberkommandos, die über eigene Generalstäbe verfügten, gab es nicht.

**Comment by ernieIzde8ski** [comment]
Der Hauptsitz des OKW war in Wünsdorf bei Zossen in der Bunkeranlage „Maybach II“, südlich von Berlin. Am jeweiligen Standort des Führerhauptquartiers gab es eine Feldstaffel.

**Comment by ernieIzde8ski** [comment]
Am 20. April 1945 verlegte das OKW seinen Sitz für drei Tage nach Wannsee, um anschließend den Sitz schrittweise über Krampnitz, Neuroofen, Dobbin, Wismar, Neustadt in Holstein zum 3. Mai 1945 in den Sonderbereich Mürwik zu verlegen, wo sich die letzte Reichsregierung und mit ihr Hitlers Nachfolger als Oberbefehlshaber, Karl Dönitz, aufhielt.

**Comment by ernieIzde8ski** [comment]
### Gründung
Adolf Hitler nutzte die Blomberg-Fritsch-Krise, die mit der Demission des Reichswehrministers Werner von Blomberg endete, um die Führungsspitze der Wehrmacht stärker auf seine Person und die NSDAP zu verpflichten. Er übernahm selbst die Funktion des Reichskriegsministers und Oberbefehlshabers und gliederte das Wehrmachtamt um zum „Oberkommando der Wehrmacht“ in der Funktion eines militärischen Generalstabs. An seine Spitze setzte er die ihm treu ergebenen Generäle Wilhelm Keitel und Alfred Jodl. Gleichzeitig erhielt das Heer mit Walther von Brauchitsch einen neuen Oberbefehlshaber, der direkten Zugang zu Hitler erhielt. Weitere sechzehn Generäle wurden von ihren Kommandostellen abgelöst. Weil die Oberbefehlshaber aller Teilstreitkräfte Vortragsrecht bei Hitler erhielten, konnte Keitel nicht mehr die Belange der Wehrmacht als Ganzes vertreten. Keitel konnte nur partiell und nur insoweit die Funktionen des stellvertretenden Kriegsministers übernehmen, wie es die Oberbefehlshaber der Teilstreitkräfte Heer, Kriegsmarine und Luftwaffe zuließen.
